module.exports = {
    ENV: 'DEVELOP',
    BASE_URL: 'http://localhost:3000/',
    // APIURL: 'http://localhost:8080/AgraCollege-BackEnd/',
    APIURL: 'http://localhost/AgraCollege-BackEnd/',
    ROLES: ['STUDENT', 'ADMIN'],
    MERCHANTID: 'BDSKUATY',
    SECURITYID: 'bdskuaty',
    PAYMENTAPI: 'https://uat.billdesk.com/pgidsk/PGIMerchantPayment',
    // RESPONSEURL: 'http://localhost:8080/AgraCollege-BackEnd/payment.php',
    RESPONSEURL: 'http://localhost/AgraCollege-BackEnd/payment.php',
    QUERYAPI: 'https://uat.billdesk.com/pgidsk/PGIQueryController',
    CAPTCHA: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
    APP_VERSION: '6.8',
    ADMIN_APP_VERSION:'5.7',
  }